# Generated by Django 5.2 on 2025-06-15 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='message',
            options={'ordering': ['created_at'], 'verbose_name': '消息表'},
        ),
        migrations.AlterModelTable(
            name='message',
            table='message',
        ),
    ]
