# Generated by Django 5.2 on 2025-06-19 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('message', '0002_alter_message_options_alter_message_table'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='file',
        ),
        migrations.AddField(
            model_name='message',
            name='file1',
            field=models.FileField(blank=True, null=True, upload_to='uploads/messages/', verbose_name='文件1'),
        ),
        migrations.AddField(
            model_name='message',
            name='file2',
            field=models.FileField(blank=True, null=True, upload_to='uploads/messages/', verbose_name='文件2'),
        ),
    ]
